version: "3.4"
services:
  htz_login_react:
    hostname: htz-login-app
    build:
      context: .
      dockerfile: Dockerfile-login
      args:
        NEXT_BUILD_ID: ${version:-latest}
    image: 'nexus-ng.themarker.com/htz-login-app:${version:-latest}'
    ports:
      - 9004:9004
    environment:
      - NODE_ENV=production
      - CONNECTION_PRESET=prod
      - NEXT_BUILD_ID=${NEXT_BUILD_ID:-latest}
      # the following environment is optional
      - PORT=9004
      - BIND_ADDRESS=login
      - HOSTNAME=login
      - GRAPHQL_USE_SSL=true
      - GRAPHQL_EXPOSE_PORT=false
      - GRAPHQL_SUB_DOMAIN=graphql-prod
    networks:
      - production
    deploy:
      replicas: 5
      update_config:
        parallelism: 5
        delay: 30s
        order: start-first
      restart_policy:
        condition: on-failure

networks:
  production:
    external: true
