version: "3.4"
services:
  htz_login_react:
    hostname: htz-login-app
    build:
      context: .
      dockerfile: Dockerfile-login
      args:
        NEXT_BUILD_ID: ${version:-latest}
    image: 'nexus-ng.themarker.com/htz-promotions-app:${version:-latest}'
    ports:
      - 9004:9004
    environment:
      - NODE_ENV=production
      - CONNECTION_PRESET=prod
      - NEXT_BUILD_ID=${NEXT_BUILD_ID:-latest}
      # the following environment is optional
      - PORT=9004
      - BIND_ADDRESS=login
      - HOSTNAME=login
      - GRAPHQL_USE_SSL=true
      - GRAPHQL_EXPOSE_PORT=false
      - GRAPHQL_SUB_DOMAIN=graphql-dev

    networks:
      - prod01

networks:
  prod01:
    external: true
