version: '3.4'
services:
  htz_graphql:
    hostname: htz-graphql
    build:
      context: .
      args:
        NEXT_BUILD_ID: ${version:-latest}
    image: 'nexus-ng.themarker.com/htz-graphql:${version:-latest}'
    ports:
      - 5209:5209
    deploy:
            replicas: 5
            update_config:
              parallelism: 5
              delay: 30s
              order: start-first
            restart_policy:
              condition: on-failure
    command: ['yarn', 'workspace', '@haaretz/haaretz.co.il', 'start:gql']
    environment:
      - NODE_ENV=production
      - CONNECTION_PRESET=prod
      - NEXT_BUILD_ID=${NEXT_BUILD_ID:-latest}
      # the following environment is optional
      - PORT=5209
      - GRAPHQL_PORT=5209
      - BIND_ADDRESS=react-stage
      - HOSTNAME=react-stage
      - GRAPHQL_USE_SSL=true
      - GRAPHQL_EXPOSE_PORT=false
      - GRAPHQL_SUB_DOMAIN=graphql-pp2p

    networks:
      - dev03

networks:
  dev03:
    external: true
