version: '3.4'
services:
  htz_graphql:
    hostname: htz-graphql
    build:
      context: .
      args:
        NEXT_BUILD_ID: ${version:-latest}
    image: 'nexus-ng.themarker.com/htz-graphql:${version:-latest}'
    ports:
      - 5201:5201
    deploy:
      replicas: 5
      update_config:
        parallelism: 5
        delay: 30s
        order: start-first
      restart_policy:
        condition: on-failure
    command: ['yarn', 'workspace', '@haaretz/haaretz.co.il', 'start:gql']
    environment:
      - NODE_ENV=production
      - CONNECTION_PRESET=prod
      - NEXT_BUILD_ID=${NEXT_BUILD_ID:-latest}
      # the following environment is optional
      - PORT=3201
      - GRAPHQL_PORT=5201
      - BIND_ADDRESS=react-stage
      - HOSTNAME=react-stage
      - GRAPHQL_USE_SSL=true
      - GRAPHQL_EXPOSE_PORT=false
      - GRAPHQL_SUB_DOMAIN=grahpql
      - ENGINE_API_KEY=service:Haaretz-Prod:6n6m0aRAYOlqR6m0_TvH6g      

    networks:
      - prod01

networks:
  prod01:
    external: true
